### ISSUE TITLE
Eslint terminated with an error: [object Object]

### ISSUE THREAD

**Issue by papigers** [zaggino/brackets-eslint#50]
**.eslintrc.json**:
```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "browser": true
  }
}
```
**package.json**:
```json
{
  ...
  "devDependencies": {
      ...,
      "babel-eslint": "^7.1.1",
      "eslint": "^3.10.2",
      "eslint-config-airbnb": "^13.0.0",
      "eslint-plugin-import": "^2.2.0",
      "eslint-plugin-jsx-a11y": "^3.0.1",
      "eslint-plugin-react": "^6.7.1",
      ....
    },
    ...
}
```

Might be relevant:
```shell
$ npm list --depth=0
...
+-- eslint@3.10.2
+-- eslint-config-airbnb@13.0.0
+-- eslint-plugin-import@2.2.0
+-- UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@3.0.1
+-- eslint-plugin-react@6.7.1
...

npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^2.2.3, required by eslint-config-airbnb@13.0.0
```

Brackets throws: 
`ESLint terminated with an error: [object Object]`

Running `eslint . --ext .js,.jsx` works fine.

**Comment by zaggino** [comment]
Can you give result of `npm ls -g --depth=0` on the machine?

**Comment by papigers** [comment]
No problem:
```
+-- abbrev@1.0.9
+-- babel-cli@6.8.0
+-- babel-eslint@6.1.0
+-- babel-plugin-transform-react-constant-elements@6.8.0
+-- babel-plugin-transform-react-inline-elements@6.8.0
+-- babel-plugin-transform-react-remove-prop-types@0.2.6
+-- bower@1.7.9
+-- cordova@6.0.0
+-- eslint@2.13.1
+-- eslint-config-airbnb@9.0.1
+-- eslint-plugin-babel@3.3.0
+-- eslint-plugin-import@1.9.2
+-- eslint-plugin-jsx-a11y@1.5.3
+-- eslint-plugin-react@5.2.2
+-- express-generator@4.13.1
+-- f@0.5.0
+-- fstream@1.0.10
+-- glob@7.0.4
+-- grunt-cli@0.1.13
+-- gulp@3.9.1
+-- heroku@0.2.0
+-- ionic@1.7.13
+-- jade@1.11.0
+-- jshint@2.9.2
+-- json-server@0.8.4
+-- karma-cli@0.1.2
+-- less@2.5.3
+-- mocha@2.5.3
+-- node-theseus@0.2.6
+-- nodemon@1.9.2
+-- npm@3.8.6
+-- npm-check-updates@2.6.7
+-- npm-package-arg@4.2.0
+-- npm-user-validate@0.1.4
+-- npmlog@3.1.2
+-- readable-stream@2.1.4
+-- webpack@1.13.0
+-- webpack-dev-server@1.14.1
+-- which@1.2.10
+-- wrappy@1.0.2
`-- yo@1.8.1
```

**Comment by zaggino** [comment]
You have `eslint-plugin-jsx-a11y` installed globally, but not in the project. That's why `eslint . --ext .js,.jsx` passes, but extension fails. Extension actually uses what you've installed inside the project, not globally.

**Comment by zaggino** [comment]
Although I admit the error message should be better, I'll try to replicate and fix it soon.

**Comment by papigers** [comment]
I do have `eslint-plugin-jsx-a11y` installed, it just was version 3.0.1, which didn't met `eslint-plugin-jsx-a11y@^2.2.3` required by `eslint-config-airbnb`. Anyway, I was trying to uninstall it and install it with the required version, now `eslint list --depth=0` prints:
```
...
+-- eslint@3.10.2
+-- eslint-config-airbnb@13.0.0
+-- eslint-plugin-import@2.2.0
+-- eslint-plugin-jsx-a11y@2.2.3
+-- eslint-plugin-react@6.7.1
...
```

Without the peer dependency error. 

The error still persists.

Could it be because of the versions mismatch between local and global installs?

**Comment by zaggino** [comment]
Try putting this to your package.json scripts:
```
"scripts": {
 "lint": "eslint . --ext .js,.jsx"
}
```
and run `npm run lint`, that should execute eslint from project resources, not from global

**Comment by zaggino** [comment]
or you can do `./node_modules/.bin/eslint . --ext .js,.jsx` too I think?

**Comment by zaggino** [comment]
eslint, its configs or plugins should be really installed globally, from my experience it causes problems when switching between projects that use different versions

**Comment by papigers** [comment]
`npm run lint` worked. I tried to uninstall local eslint, configs and plugins, and brackets now throws:
`ESLintError: You need to install ESLint in your project folder with npm install eslint` (didn't touch global installations)

**Comment by zaggino** [comment]
I've tried to recreate what you posted above but my error is different, can you give me a sample I can clone/download to replicate this?

![image](https://cloud.githubusercontent.com/assets/1067319/20472632/5662b38c-b00f-11e6-86c4-339784fb7fe3.png)

**Comment by zaggino** [comment]
Btw be sure to be using latest version (1.8 http://brackets.io/ or 1.9 https://github.com/zaggino/brackets-electron/releases)

**Comment by papigers** [comment]
I'm running 1.8 brackets.
I've added you as a collab to my project so you could clone it.

**Comment by zaggino** [comment]
```
git clone https://github.com/papigers/Drones
cd Drones
npm install
```
got 3 warnings
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
```
open with Brackets, switch project to the directory, open a jsx file:
![image](https://cloud.githubusercontent.com/assets/1067319/20474173/570057f4-b019-11e6-820f-413ed6128896.png)

**Comment by zaggino** [comment]
Change package.json: 
![image](https://cloud.githubusercontent.com/assets/1067319/20474290/168ceef2-b01a-11e6-8c85-f5857f14b0ab.png)

Then in shell:
```
Zaggi@ZAGGI-PC MINGW64 /d/dev/Drones (master)
$ npm run test

> drones-mouseux@1.0.0 test D:\dev\Drones
> eslint . --ext js,jsx

D:\dev\Drones\node_modules\eslint-config-airbnb\rules\react-a11y.js:
        Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
        Value "" is the wrong type.

Referenced from: airbnb
Referenced from: D:\dev\Drones\.eslintrc.json
Error: D:\dev\Drones\node_modules\eslint-config-airbnb\rules\react-a11y.js:
        Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
        Value "" is the wrong type.

Referenced from: airbnb
Referenced from: D:\dev\Drones\.eslintrc.json
    at validateRuleOptions (D:\dev\Drones\node_modules\eslint\lib\config\config-validator.js:115:15)
    at Object.keys.forEach.id (D:\dev\Drones\node_modules\eslint\lib\config\config-validator.js:162:13)
    at Array.forEach (native)
    at Object.validate (D:\dev\Drones\node_modules\eslint\lib\config\config-validator.js:161:35)
    at load (D:\dev\Drones\node_modules\eslint\lib\config\config-file.js:522:19)
    at configExtends.reduceRight.e (D:\dev\Drones\node_modules\eslint\lib\config\config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (D:\dev\Drones\node_modules\eslint\lib\config\config-file.js:362:28)
    at load (D:\dev\Drones\node_modules\eslint\lib\config\config-file.js:529:22)
    at configExtends.reduceRight.e (D:\dev\Drones\node_modules\eslint\lib\config\config-file.js:391:36)

```

**Comment by zaggino** [comment]
To me it seems like extension is consistent with the script.

**Comment by papigers** [comment]
Any idea why you see the error properly and I don't? 

Also, could you try:
```
npm uninstall --save-dev eslint-plugin-jsx-a11y
npm install --save-dev eslint-plugin-jsx-a11y@^2.2.3
```
And check for me if that solves the problem, please?

**Comment by zaggino** [comment]
What node version are you using? Brackets 1.8 contains Node 6.3.1, my pc is 6.9.1. Anything else then 6.x will probably cause different results.

**Comment by zaggino** [comment]
```
npm uninstall --save-dev eslint-plugin-jsx-a11y
npm install --save-dev eslint-plugin-jsx-a11y@^2.2.3
```
Fixed the issue. You can read more about it here: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/116

```
$ npm test

> drones-mouseux@1.0.0 test D:\dev\Drones
> eslint . --ext js,jsx


D:\dev\Drones\components\App.jsx
   3:1   error  'navbar' should be listed in the project's dependencies. Run 'npm i -S navbar' to add it  import/no-extraneous-dependencies
   3:20  error  Unable to resolve path to module 'navbar'                                                 import/no-unresolved
   3:20  error  Missing file extension for "navbar"                                                       import/extensions
   5:8   error  's' is defined but never used                                                             no-unused-vars
   7:16  error  Component should be written as a pure function                                            react/prefer-stateless-function
   7:49  error  Missing space before opening brace                                                        space-before-blocks
  16:2   error  Unnecessary semicolon                                                                     no-extra-semi
  16:3   error  Newline required at end of file but not found                                             eol-last
...
```

**Comment by zaggino** [comment]
It also fixed the issue in brackets, be sure to have Node 6 installed on your system.

**Comment by papigers** [comment]
Updating node solved the problem, thanks!

**Comment by Semaho** [comment]
Hello, I'm running Brackets 1.9 and just updated Node, still have the issue.
I can give more info, just ask!

**Comment by Cammac7** [comment]
@zaggino I am also having this issue. Running Brackets 1.13, and npm 6.4.1

**Comment by zaggino** [comment]
@Semaho I don't maintain this project anymore.
